### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [analysis-kuromoji] is incompatible with Elasticsearch [2.3.4]. Was designed for version [2.3.2]

### ISSUE THREAD

**Issue by hdknr** [hdknr/scriptogr.am#18]
~~~
$ sudo grep elasticsearch /var/log/syslog
Sep  3 11:14:57 jessie elasticsearch[15578]: [2016-09-03 11:14:57,443][INFO ][node                     ] [Jack O'Lantern] version[2.3.4], pid[15578], build[e455fd0/2016-06-30T11:24:31Z]
Sep  3 11:14:57 jessie elasticsearch[15578]: [2016-09-03 11:14:57,447][INFO ][node                     ] [Jack O'Lantern] initializing ...
Sep  3 11:14:58 jessie elasticsearch[15578]: Exception in thread "main" java.lang.IllegalArgumentException: Plugin [analysis-kuromoji] is incompatible with Elasticsearch [2.3.4]. Was designed for version [2.3.2]
Sep  3 11:14:58 jessie elasticsearch[15578]: at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:118)
Sep  3 11:14:58 jessie elasticsearch[15578]: at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
Sep  3 11:14:58 jessie elasticsearch[15578]: at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
Sep  3 11:14:58 jessie elasticsearch[15578]: at org.elasticsearch.node.Node.<init>(Node.java:158)
Sep  3 11:14:58 jessie elasticsearch[15578]: at org.elasticsearch.node.Node.<init>(Node.java:140)
Sep  3 11:14:58 jessie elasticsearch[15578]: at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
Sep  3 11:14:58 jessie elasticsearch[15578]: at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
Sep  3 11:14:58 jessie elasticsearch[15578]: at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
Sep  3 11:14:58 jessie elasticsearch[15578]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Sep  3 11:14:58 jessie elasticsearch[15578]: Refer to the log for complete error details.
Sep  3 11:14:58 jessie systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Sep  3 11:14:58 jessie systemd[1]: Unit elasticsearch.service entered failed state.
~~~

**Comment by hdknr** [comment]
~~~
$ sudo -u elasticsearch /usr/share/elasticsearch/bin/plugin install analysis-kuromoji                      
-> Installing analysis-kuromoji...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/analysis-kuromoji/2.3.4/analysis-kuromoji-2.3.4.zip ...
Downloading .........................................DONE
Verifying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/analysis-kuromoji/2.3.4/analysis-kuromoji-2.3.4.zip checksums if available ...
Downloading .DONE
ERROR: plugin directory /usr/share/elasticsearch/plugins/analysis-kuromoji already exists. To update the plugin, uninstall it first using 'remove analysis-kuromoji' command
~~~

**Comment by hdknr** [comment]
~~~
$ sudo apt-get update && sudo apt-get upgrade

$ dpkg -l | grep elasticsearch
ii  elasticsearch                       2.4.0                                all          Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html
~~~

~~~
$ sudo /usr/share/elasticsearch/bin/plugin remove analysis-kuromoji                        
-> Removing analysis-kuromoji...
Removed analysis-kuromoji


$ sudo /usr/share/elasticsearch/bin/plugin install analysis-kuromoji                                        
-> Installing analysis-kuromoji...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/analysis-kuromoji/2.4.0/analysis-kuromoji-2.4.0.zip ...
Downloading ............DONE
Verifying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/analysis-kuromoji/2.4.0/analysis-kuromoji-2.4.0.zip checksums if available ...
Downloading .DONE
Installed analysis-kuromoji into /usr/share/elasticsearch/plugins/analysis-kuromoji
~~~

~~~
$ sudo /etc/init.d/elasticsearch start
[ ok ] Starting elasticsearch (via systemctl): elasticsearch.service.
$ sudo lsof -u elasticsearch | grep TCP            
java    813 elasticsearch   85u  IPv6            5322329      0t0     TCP localhost:9300 (LISTEN)
java    813 elasticsearch   87u  IPv6            5322332      0t0     TCP localhost:9300 (LISTEN)
java    813 elasticsearch   98u  IPv6            5322387      0t0     TCP localhost:9200 (LISTEN)
java    813 elasticsearch   99u  IPv6            5322388      0t0     TCP localhost:9200 (LISTEN)
~~~
