### ISSUE TITLE
Unable to establish a connection with the SafariDriver extension

### ISSUE THREAD

**Issue by hdknr** [hdknr/scriptogr.am#19]
~~~
SafariDriver Launcher

[  0.005s] [safaridriver.client] Connecting to SafariDriver browser extension...
[  0.023s] [safaridriver.client] This will fail if you have not installed the latest SafariDriver extension from
http://selenium-release.storage.googleapis.com/index.html
[  0.023s] [safaridriver.client] Extension logs may be viewed by clicking the Selenium [✓] button on the Safari toolbar
[  2.567s] [safaridriver.client] Unable to establish a connection with the SafariDriver extension
~~~

**Comment by hdknr** [comment]
~~~bash 
$ ./connect.bash 
/usr/local/Cellar/selenium-server-standalone/2.53.1/libexec/selenium-server-standalone-2.53.1.jar
11:01:08.443 INFO - Launching a standalone Selenium Server
11:01:08.472 INFO - Java: Oracle Corporation 24.79-b02
11:01:08.472 INFO - OS: Mac OS X 10.11.6 x86_64
11:01:08.489 INFO - v2.53.1, with Core v2.53.1. Built from revision a36b8b1
11:01:08.579 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match the current platform MAC
11:01:08.579 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{platform=WINDOWS, browserName=MicrosoftEdge, version=}] does not match the current platform MAC
11:01:08.579 INFO - Driver class not found: com.opera.core.systems.OperaDriver
11:01:08.579 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
11:01:08.581 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
11:01:08.581 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
11:01:08.649 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:49950/wd/hub
11:01:08.649 INFO - Selenium Server is up and running
11:01:18.463 INFO - Executing: [new session: Capabilities [{platform=MAC, javascriptEnabled=true, browserName=safari, version=}]])
11:01:18.473 INFO - Creating a new session for Capabilities [{platform=MAC, javascriptEnabled=true, browserName=safari, version=}]
11:01:18.552 INFO - Server started on port 21223
11:01:18.562 INFO - Launching Safari
11:01:18.573 INFO - Waiting for SafariDriver to connect
11:01:28.578 INFO - Shutting down
11:01:28.579 INFO - Stopping Safari
11:01:28.644 INFO - Stopping server
11:01:28.645 INFO - Stopping server
11:01:28.655 INFO - Shutdown complete
11:01:28.656 INFO - Shutting down
11:01:28.656 INFO - Stopping server
11:01:28.656 INFO - Shutdown complete
11:01:28.660 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'Peeko.local', ip: '192.168.10.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.7.0_79'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:124)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:79)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:204)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:166)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'Peeko.local', ip: '192.168.10.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.7.0_79'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:113)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:97)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:103)
	... 9 more
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Failed to connect to SafariDriver after 10082 ms
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'Peeko.local', ip: '192.168.10.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.7.0_79'
Driver info: driver.version: SafariDriver
	at org.openqa.selenium.safari.SafariDriverCommandExecutor.start(SafariDriverCommandExecutor.java:121)
	at org.openqa.selenium.safari.SafariDriver.startClient(SafariDriver.java:76)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:62)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:53)
	... 14 more
11:01:28.672 WARN - Exception: Failed to connect to SafariDriver after 10082 ms
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'Peeko.local', ip: '192.168.10.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.7.0_79'
Driver info: driver.version: SafariDriver
Traceback (most recent call last):
  File "safari.py", line 38, in <module>
    br = webdriver.Safari()
  File "/Users/hide/ve/tact/lib/python2.7/site-packages/selenium/webdriver/safari/webdriver.py", line 60, in __init__
    desired_capabilities=desired_capabilities)
  File "/Users/hide/ve/tact/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Users/hide/ve/tact/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/Users/hide/ve/tact/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Users/hide/ve/tact/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to connect to SafariDriver after 10082 ms
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'Peeko.local', ip: '192.168.10.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.7.0_79'
Driver info: driver.version: SafariDriver
Stacktrace:
    at org.openqa.selenium.safari.SafariDriverCommandExecutor.start (SafariDriverCommandExecutor.java:121)
    at org.openqa.selenium.safari.SafariDriver.startClient (SafariDriver.java:76)
    at org.openqa.selenium.remote.RemoteWebDriver.<init> (RemoteWebDriver.java:119)
    at org.openqa.selenium.remote.RemoteWebDriver.<init> (RemoteWebDriver.java:144)
    at org.openqa.selenium.safari.SafariDriver.<init> (SafariDriver.java:62)
    at org.openqa.selenium.safari.SafariDriver.<init> (SafariDriver.java:53)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0 (NativeConstructorAccessorImpl.java:-2)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance (NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:526)
    at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor (DefaultDriverProvider.java:103)
    at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance (DefaultDriverProvider.java:97)
    at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance (DefaultDriverFactory.java:60)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call (DefaultSession.java:222)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call (DefaultSession.java:1)
    at java.util.concurrent.FutureTask.run (FutureTask.java:262)
    at org.openqa.selenium.remote.server.DefaultSession$1.run (DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:615)
    at java.lang.Thread.run (Thread.java:745)
~~~

**Comment by hdknr** [comment]
~~~bash 
$ pip install selenium==2.53.1 -U
Collecting selenium==2.53.1
  Using cached selenium-2.53.1-py2-none-any.whl
Installing collected packages: selenium
  Found existing installation: selenium 2.53.6
    Uninstalling selenium-2.53.6:
      Successfully uninstalled selenium-2.53.6
Successfully installed selenium-2.53.1
~~~
