### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /var/folders/3n/0lk686q1129clzkw38blpwdc0000gp/T/tmpxp7MeV If you specified a log_file in the FirefoxBinary constructor, check it for details.

### ISSUE THREAD

**Issue by hdknr** [hdknr/scriptogr.am#20]
~~~
/usr/local/Cellar/selenium-server-standalone/2.53.1/libexec/selenium-server-standalone-2.53.1.jar
Traceback (most recent call last):
  File "firefox.py", line 38, in <module>
    br = webdriver.Firefox()
  File "/Users/hide/ve/tact/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/Users/hide/ve/tact/lib/python2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/Users/hide/ve/tact/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/Users/hide/ve/tact/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /var/folders/3n/0lk686q1129clzkw38blpwdc0000gp/T/tmpxp7MeV If you specified a log_file in the FirefoxBinary constructor, check it for details.
~~~

**Comment by hdknr** [comment]
~~~bash 
$ brew install geckodriver
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
zplug

==> Downloading https://homebrew.bintray.com/bottles/geckodriver-0.10.0.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring geckodriver-0.10.0.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/geckodriver/0.10.0: 6 files, 12.5M
~~~

**Comment by hdknr** [comment]
- https://github.com/SeleniumHQ/selenium/issues/2739
