### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/graylog2/bootstrap/Main : Unsupported major.m inor version 52.0

### ISSUE THREAD

**Issue by hdknr** [hdknr/scriptogr.am#22]
~~~
Oct 12 07:16:21 jessie graylog-server[13770]: Exception in thread "main" java.lang.UnsupportedClassVersionError: org/graylog2/bootstrap/Main : Unsupported major.m
inor version 52.0
Oct 12 07:16:21 jessie graylog-server[13770]: at java.lang.ClassLoader.defineClass1(Native Method)
Oct 12 07:16:21 jessie graylog-server[13770]: at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
Oct 12 07:16:21 jessie graylog-server[13770]: at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
Oct 12 07:16:21 jessie graylog-server[13770]: at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
Oct 12 07:16:21 jessie graylog-server[13770]: at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
Oct 12 07:16:21 jessie graylog-server[13770]: at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
Oct 12 07:16:21 jessie graylog-server[13770]: at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
Oct 12 07:16:21 jessie graylog-server[13770]: at java.security.AccessController.doPrivileged(Native Method)
Oct 12 07:16:21 jessie graylog-server[13770]: at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
Oct 12 07:16:21 jessie graylog-server[13770]: at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
Oct 12 07:16:21 jessie graylog-server[13770]: at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
Oct 12 07:16:21 jessie graylog-server[13770]: at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
Oct 12 07:16:21 jessie graylog-server[13770]: at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Oct 12 07:16:21 jessie systemd[1]: graylog-server.service: main process exited, code=exited, status=1/FAILURE
Oct 12 07:16:21 jessie systemd[1]: Unit graylog-server.service entered failed state.
~~~

**Comment by hdknr** [comment]
~~~bash 
$ sudo apt-get install openjdk-8-jre openjdk-8-jdk -y
~~~

**Comment by hdknr** [comment]
~~~
2016-10-12T08:04:27.383Z INFO  [CmdLineTool] Loaded plugin: Elastic Beats Input 1.1.1 [org.graylog.plugins.beats.BeatsInputPlugin]
2016-10-12T08:04:27.390Z INFO  [CmdLineTool] Loaded plugin: Collector 1.1.1 [org.graylog.plugins.collector.CollectorPlugin]
2016-10-12T08:04:27.393Z INFO  [CmdLineTool] Loaded plugin: Enterprise Integration Plugin 1.1.1 [org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin]
2016-10-12T08:04:27.395Z INFO  [CmdLineTool] Loaded plugin: MapWidgetPlugin 1.1.1 [org.graylog.plugins.map.MapWidgetPlugin]
2016-10-12T08:04:27.396Z INFO  [CmdLineTool] Loaded plugin: Pipeline Processor Plugin 1.1.1 [org.graylog.plugins.pipelineprocessor.ProcessorPlugin]
2016-10-12T08:04:27.397Z INFO  [CmdLineTool] Loaded plugin: Anonymous Usage Statistics 2.1.1 [org.graylog.plugins.usagestatistics.UsageStatsPlugin]
2016-10-12T08:04:27.435Z ERROR [CmdLineTool] Invalid configuration
com.github.joschi.jadconfig.ValidationException: Parameter password_secret should not be blank
        at com.github.joschi.jadconfig.validators.StringNotBlankValidator.validate(StringNotBlankValidator.java:25) ~[graylog.jar:?]
        at com.github.joschi.jadconfig.validators.StringNotBlankValidator.validate(StringNotBlankValidator.java:11) ~[graylog.jar:?]
        at com.github.joschi.jadconfig.JadConfig.validateParameter(JadConfig.java:215) ~[graylog.jar:?]
        at com.github.joschi.jadconfig.JadConfig.processClassFields(JadConfig.java:148) ~[graylog.jar:?]
        at com.github.joschi.jadconfig.JadConfig.process(JadConfig.java:99) ~[graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.processConfiguration(CmdLineTool.java:351) [graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.readConfiguration(CmdLineTool.java:344) [graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:177) [graylog.jar:?]
        at org.graylog2.bootstrap.Main.main(Main.java:44) [graylog.jar:?]
~~~

**Comment by hdknr** [comment]
~~~
2016-10-12T08:21:05.965Z INFO  [cluster] No server chosen by WritableServerSelector from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: 接続を拒否されました}}]}. Waiting for 30000 ms before timing out
~~~

**Comment by hdknr** [comment]
~~~bash
$ sudo mkdir /home/mongodb
$ sudo chown mongodb:nogroup /home/mongodb
~~~

~~~bash
$ sudo lsof -i:27017
COMMAND   PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
java    22404 graylog   37u  IPv6 532087      0t0  TCP localhost:40602->localhost:27017 (ESTABLISHED)
java    22404 graylog   38u  IPv6 532089      0t0  TCP localhost:40603->localhost:27017 (ESTABLISHED)
mongod  22861 mongodb    9u  IPv4 532084      0t0  TCP localhost:27017 (LISTEN)
mongod  22861 mongodb   12u  IPv4 532088      0t0  TCP localhost:27017->localhost:40602 (ESTABLISHED)
mongod  22861 mongodb   13u  IPv4 532090      0t0  TCP localhost:27017->localhost:40603 (ESTABLISHED)
~~~
